#!/bin/bash
set -e

version=$(grep '^SDK_VERSION_NAME=' gradle.properties | cut -d '=' -f2)

is_beta=false
if [[ $version == *"rc"* ]]; then
  is_beta=true
fi

branch=${GITHUB_REF#refs/heads/}

echo "Version: $version"
echo "Is Beta: $is_beta"
echo "Branch: $branch"

echo "Fetching tags from remote repository."
git fetch --tags

if git rev-parse "$version" >/dev/null 2>&1; then
  echo "Local tag $version already exists."
else
  echo "Creating local tag $version."
  git tag $version
fi

if git ls-remote --tags origin | grep -q "refs/tags/$version"; then
  echo "Remote tag $version already exists."
else
  echo "Pushing local tag $version to remote."
  git push origin $version
fi

# Create release
release_title="Release $version"
text="Autogenerated release. Check more details at [Mindbox SDK Documentation](https://developers.mindbox.ru/docs/androidhuawei-native-sdk)"

echo "Release title: $release_title"
echo "Text: $text"

prerelease_flag=$([ "$is_beta" = true ] && echo "--prerelease" || echo "")

gh release create "$version" --target "$branch" --title "$release_title" --notes "$text" $prerelease_flag

echo "Release $version created for repo on branch $branch"
