#!/usr/bin/env bash
set -euo pipefail

version=$(grep '^SDK_VERSION_NAME=' gradle.properties | cut -d '=' -f2)

is_beta=false
if [[ $version == *"rc"* ]]; then
  is_beta=true
fi

branch=${RELEASE_BRANCH:-${GITHUB_REF:-}}
branch=${branch#refs/heads/}

echo "Version: $version"
echo "Is Beta: $is_beta"
echo "Branch: $branch"

echo "Fetching tags from remote repository."
git fetch --tags

if git rev-parse -q --verify "refs/tags/$version" >/dev/null; then
  echo "Local tag $version already exists."
else
  echo "Creating local tag $version."
  git tag "$version"
fi

if [ -n "$(git ls-remote --tags origin "refs/tags/$version")" ]; then
  echo "Remote tag $version already exists."
else
  echo "Pushing local tag $version to remote."
  git push origin "$version"
fi

# Create release
release_title="Release $version"
text="Autogenerated release. Check more details at [Mindbox SDK Documentation](https://developers.mindbox.ru/docs/android-sdk)"

echo "Release title: $release_title"
echo "Text: $text"

release_args=("$version" --target "$branch" --title "$release_title" --notes "$text")
if [ "$is_beta" = true ]; then
  release_args+=(--prerelease)
fi

gh release create "${release_args[@]}"

echo "Release $version created for repo on branch $branch"
