name: Distribute PushOk

on:
  pull_request:
    types: [ closed ]
    branches:
      - develop
  push:
    branches:
      - 'release/*'
      - 'support/*'
      - 'poziev/change-trigger-job'

jobs:
  distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last 3 commit messages
        run: |
          commits=$(git log -3 --pretty=format:"%s")
          echo "commits=$commits" >> $GITHUB_ENV 

      - name: Trigger build & send to FAD
        run: |
          curl --location 'https://mindbox.gitlab.yandexcloud.net/api/v4/projects/868/trigger/pipeline' \
            --form 'token="glptt-74df0063bac887544d1627ed2b8688c88696217a"' \
            --form 'ref="test_branch"' \
            --form "variables[INPUT_BRANCH]=\"${{ github.head_ref || github.ref_name }}\"" \
            --form "variables[INPUT_COMMITS]=\"${{ env.commits }}\""
