name: Distribute PushOk (manual)

on:
  workflow_dispatch:
    inputs:
      app_ref:
        description: "GitLab App branch (Optional)"
        required: false
        default: ""

permissions:
  contents: read

jobs:
  call-reusable:
    uses: ./.github/workflows/distribute-reusable.yml
    with:
      branch: ${{ github.ref_name }}
      app_ref: ${{ inputs.app_ref }}
    secrets:
      GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
