name: SDK publish RC manual


on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch matches pattern
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          if ! echo "$REF_NAME" | grep -q "release/.*-rc"; then
            echo "Branch name must match pattern 'release/*-rc' (e.g. release/2.13.2-rc)"
            exit 1
          fi

  call-publish-reusable:
    needs: check-branch
    permissions:
      contents: write
    uses: ./.github/workflows/publish-reusable.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      GPGKEYCONTENTS: ${{ secrets.GPGKEYCONTENTS }}
      SECRETPASSPHRASE: ${{ secrets.SECRETPASSPHRASE }}
      SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}
      SIGNINGKEYID: ${{ secrets.SIGNINGKEYID }}
      CENTER_PORTAL_USERNAME: ${{ secrets.CENTER_PORTAL_USERNAME }}
      CENTER_PORTAL_PASSWORD: ${{ secrets.CENTER_PORTAL_PASSWORD }}
      PAT_FOR_TRIGGERING_BRANCH_PROTECTION: ${{ secrets.PAT_FOR_TRIGGERING_BRANCH_PROTECTION }}
